# Generated by Django 5.0.6 on 2025-04-05 18:03

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.PositiveIntegerField(default=auction.models.Auction.random_id, editable=False, primary_key=True, serialize=False)),
                ('starting_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('starting_bid', models.IntegerField()),
                ('time_frame', models.IntegerField()),
            ],
        ),
    ]
