# Generated by Django 5.0.6 on 2025-03-22 21:33

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.PositiveIntegerField(default=auction.models.Auction.random_id, editable=False, primary_key=True, serialize=False)),
                ('startingDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('startingBid', models.IntegerField()),
                ('timeFrame', models.IntegerField()),
            ],
        ),
    ]
