# Generated by Django 5.0.6 on 2025-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='startingBid',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='startingDate',
            new_name='starting_date',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='timeFrame',
            new_name='time_frame',
        ),
    ]
