# Generated by Django 5.0.6 on 2025-04-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekdays', models.CharField(help_text="Format: '0,1,5' for Monday, Tuesday and Saturday", max_length=13)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Higher number = higher priority')),
            ],
            options={
                'verbose_name': 'Group Schedule',
                'verbose_name_plural': 'Group Schedules',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='SpecificSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Specific Schedule',
                'verbose_name_plural': 'Specific Schedules',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(default='#3498db', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bookable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
            },
        ),
        migrations.CreateModel(
            name='SlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('group_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.groupschedule')),
                ('specific_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.specificschedule')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='specificschedule',
            name='time_slots',
            field=models.ManyToManyField(through='schedule.SlotAssignment', to='schedule.timeslot'),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='time_slots',
            field=models.ManyToManyField(through='schedule.SlotAssignment', to='schedule.timeslot'),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_slots', models.ManyToManyField(through='schedule.SlotAssignment', to='schedule.timeslot')),
            ],
            options={
                'verbose_name': 'Weekly Schedule',
                'verbose_name_plural': 'Weekly Schedules',
                'unique_together': {('weekday',)},
            },
        ),
        migrations.AddField(
            model_name='slotassignment',
            name='weekly_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.weeklyschedule'),
        ),
    ]
