# Generated by Django 5.0.6 on 2025-04-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateField(unique=True)),
                ('precio', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Horario Específico',
                'verbose_name_plural': 'Horarios Específicos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HorarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_semana', models.CharField(help_text="Formato: '0,1,5' para Lunes, Martes y Sábado", max_length=13)),
                ('prioridad', models.PositiveSmallIntegerField(default=10, help_text='Mayor número = mayor prioridad')),
                ('precio', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Grupo de Horarios',
                'verbose_name_plural': 'Grupos de Horarios',
                'ordering': ['-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='HorarioPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('color', models.CharField(default='#3498db', max_length=20)),
            ],
            options={
                'verbose_name': 'Periodo de Horario',
                'verbose_name_plural': 'Periodos de Horario',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('horario_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.horarioespecifico')),
                ('horario_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.horariogrupo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.horarioperiodo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='horariogrupo',
            name='periodos',
            field=models.ManyToManyField(through='schedule.AsignacionPeriodo', to='schedule.horarioperiodo'),
        ),
        migrations.AddField(
            model_name='horarioespecifico',
            name='periodos',
            field=models.ManyToManyField(through='schedule.AsignacionPeriodo', to='schedule.horarioperiodo'),
        ),
        migrations.CreateModel(
            name='HorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('precio', models.PositiveIntegerField()),
                ('periodos', models.ManyToManyField(through='schedule.AsignacionPeriodo', to='schedule.horarioperiodo')),
            ],
            options={
                'verbose_name': 'Horario Semanal',
                'verbose_name_plural': 'Horarios Semanales',
                'unique_together': {('dia_semana',)},
            },
        ),
        migrations.AddField(
            model_name='asignacionperiodo',
            name='horario_semanal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.horariosemanal'),
        ),
    ]
