# Generated by Django 5.0.6 on 2025-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioespecifico',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='horariogrupo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='horariosemanal',
            name='precio',
        ),
        migrations.AddField(
            model_name='horarioperiodo',
            name='precio',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
