# Generated by Django 5.0.6 on 2025-04-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='bookable',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='price',
        ),
    ]
