# Generated by Django 5.0.6 on 2025-03-22 21:33

import django.db.models.deletion
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.PositiveIntegerField(default=service.models.Service.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('reservable', models.BooleanField(blank=True, default=True, null=True)),
                ('maxReservation', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.establishment')),
            ],
        ),
    ]
