# Generated by Django 5.0.6 on 2025-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
