# Generated by Django 5.0.6 on 2025-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='maxReservation',
            new_name='max_reservation',
        ),
    ]
