# Generated by Django 5.0.6 on 2025-06-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_people',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
