# Generated by Django 5.0.6 on 2025-06-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_max_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
