# Generated by Django 5.0.6 on 2025-04-05 21:04

import django.db.models.deletion
import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('service', '0002_servicepriceassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.PositiveIntegerField(default=reservation.models.Reservation.random_id, editable=False, primary_key=True, serialize=False)),
                ('starting_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
