# Generated by Django 5.0.6 on 2025-03-22 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('worker', 'Worker')], default='client', max_length=100),
        ),
    ]
