# Generated by Django 5.0.6 on 2025-04-05 18:03

import django.db.models.deletion
import establishment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.PositiveIntegerField(default=establishment.models.Establishment.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('platforms', models.CharField(max_length=100)),
                ('preferences', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('free', 'Free')], default='free', max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
                ('workers', models.ManyToManyField(blank=True, related_name='establishment_workers', to='worker.worker', verbose_name='workers')),
            ],
        ),
    ]
