# Generated by Django 5.0.6 on 2025-05-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment',
            old_name='preferences',
            new_name='subscription',
        ),
    ]
