# Generated by Django 5.0.6 on 2025-03-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
    ]
