# Generated by Django 5.0.6 on 2025-03-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_alter_establishment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='user',
        ),
    ]
