# Generated by Django 5.0.6 on 2025-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_rename_preferences_establishment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='customer_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='subscription',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=50, null=True),
        ),
    ]
