# Generated by Django 5.0.6 on 2025-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_establishment_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=50, null=True),
        ),
    ]
