# Generated by Django 5.0.6 on 2025-06-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_alter_establishment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
