# Generated by Django 5.0.6 on 2025-04-05 18:03

import client.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.PositiveIntegerField(default=client.models.Client.random_id, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50)),
                ('zip_code', models.PositiveIntegerField(default=12345, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='El código postal debe contener 5 dígitos numéricos.')])),
                ('credits', models.IntegerField()),
                ('preferences', models.CharField(max_length=100)),
            ],
        ),
    ]
