# Generated by Django 5.0.6 on 2025-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='zipCode',
            new_name='zip_code',
        ),
    ]
