# Generated by Django 5.0.6 on 2025-04-05 18:03

import bid.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.PositiveIntegerField(default=bid.models.Bid.random_id, editable=False, primary_key=True, serialize=False)),
                ('send_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 5, 18, 2, 59, 907719))),
                ('event', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('winner', models.BooleanField(blank=True, default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
            ],
        ),
    ]
