# Generated by Django 5.0.6 on 2024-05-15 20:23

import bid.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0002_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.PositiveIntegerField(default=bid.models.Bid.random_id, editable=False, primary_key=True, serialize=False)),
                ('sendDate', models.DateTimeField()),
                ('event', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('winner', models.BooleanField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
