# Generated by Django 5.0.6 on 2025-03-22 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='sendDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 21, 37, 9, 323481)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
