# Generated by Django 5.0.6 on 2025-03-25 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_alter_bid_senddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='sendDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 21, 26, 55, 457176)),
        ),
    ]
