# Generated by Django 5.0.6 on 2025-03-27 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_alter_bid_senddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='sendDate',
        ),
        migrations.AddField(
            model_name='bid',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 17, 34, 9, 876767)),
        ),
    ]
