# Generated by Django 5.0.6 on 2025-03-31 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_remove_bid_senddate_bid_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='send_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 31, 12, 50, 44, 535762)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
