# Generated by Django 5.0.6 on 2025-04-08 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0011_alter_bid_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='send_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 8, 22, 23, 47, 101781)),
        ),
    ]
