# Generated by Django 5.0.6 on 2025-04-09 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0012_alter_bid_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='send_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 21, 45, 17, 65339)),
        ),
    ]
