# Generated by Django 5.0.6 on 2025-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0015_alter_bid_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='send_date',
            field=models.DateTimeField(),
        ),
    ]
