name: "Codacy Analysis con resultados guardados"

on:
  push:
    branches: [ main, develop, feat_development ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 6'  # Sábados a medianoche

jobs:
  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Ejecutar el análisis de Codacy con salida a archivo
      - name: Run Codacy Analysis
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          # Crear directorio para resultados
          mkdir -p codacy-results
          
          # Ejecutar Codacy con Docker y guardar resultados en archivo
          docker run \
            --rm \
            -v $(pwd):/code \
            -v $(pwd)/codacy-results:/results \
            -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN \
            codacy/codacy-analysis-cli:latest \
            analyze \
            --directory /code \
            --format json \
            --output /results/codacy-result.json \
            --verbose
          
          echo "Análisis completado. Resultados guardados en codacy-results/codacy-result.json"
      
      # Guardar resultados como artefacto
      - name: Guardar resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: codacy-analysis-results
          path: codacy-results/
          retention-days: 30